### ISSUE TITLE
Unable to build on Ubuntu Trusty

### ISSUE THREAD

**Issue by si-mikey** [centaurean/sharc#19]
Trying to run 'make' and getting the following error:

mikey@euler-hub:~/sharc=>  make
make[1]: Entering directory `/home/mikey/sharc/src/density'
make[1]: *** No rule to make target `compile'.  Stop.
make[1]: Leaving directory `/home/mikey/sharc/src/density'
make: *** [compile-submodules] Error 2

OS Build:
Description: Ubuntu 14.04.2 LTS
Release:	14.04

**Comment by gpnuma** [comment]
Hello, just run

    git submodule update --init --recursive

And then make, the submodule update got commented out by error in the Makefile. Thanks !

**Comment by gpnuma** [comment]
Fixed in 421bd85cdaf8e4ef36dca1b440e63b4cfff2ecf1
